### ISSUE TITLE
[Question] What should the API URL be?

### ISSUE THREAD

**Issue by poperigby** [hslatman/caddy-crowdsec-bouncer#11]
I'm running both Caddy and CrowdSec in a Docker Compose project, so I'm not really sure what the `api_url` should be set to. Should it just be the hostname of the Caddy container, along with the HTTP port (i.e. `caddy:80`).

**Comment by hslatman** [comment]
Hi @lumbo7332,

Yes, that should work. An example of a configuration that works with Compose can be found here: https://github.com/hslatman/caddy-crowdsec-bouncer/blob/main/docker/config.json. The docker-compose is in the root of the repository and contains a service called crowdsec.

**Comment by lumbo7332** [comment]
Thanks! I just needed to expose the ports in the Compose file.

**Comment by lumbo7332** [comment]
Wait, I don't think that actually worked. This is getting spammed in the Caddy log:
```
time="2022-01-21T03:25:54Z" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 172.27.0.11:8180: connect: connection refused"
```

**Comment by lumbo7332** [comment]
`docker-compose.yml`
```
services:
  caddy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./users.json:/etc/caddy/auth/local/users.json
      - data:/data
      - config:/config
      - log:/var/log/caddy
    environment:
      - PUID=1000
      - PGID=1000
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    hostname: crowdsec
    ports:
      - 8180:8180
    volumes:
        - ./acquis.yaml:/etc/crowdsec/acquis.yaml
        - log:/var/log/caddy
    environment:
        - COLLECTIONS=crowdsecurity/sshd crowdsecurity/caddy-logs
volumes:
  data:
  config:
  log:
networks:
  default:
    name: reverse_proxy
    external: true
```
`Caddyfile` snippet
```
crowdsec {
    api_url http://crowdsec:8180/
    api_key 2939239f64eae9a07b7c2b2d6410482a
    ticker_interval 15s
}
```
