### ISSUE TITLE
cannot get bouncer to enforce bans

### ISSUE THREAD

**Issue by cellulosa** [hslatman/caddy-crowdsec-bouncer#33]
hi there and thank you for the great work with this!

I am running crowdsec and caddy via docker, and a series of locally-hosted domains reached both locally (/etc/hosts) and via a cloudflared tunnel. All latest versions.

I can access my containers fine on both LAN and externally, and if I enable and inspect Caddy's access logs I can see the correct `X-Forwarded-For` address in both cases. However, if I try and run `docker exec crowdsec cscli decisions add --ip` on that ip (and also /24 ranges) I can still access all domains fine.

I am guessing it has to do with the bouncer? Any idea what it could be?

As for my config, here's what have:

docker-compose:
```
  caddy:
    container_name: caddy
    image: caddy:latest
    build:
      context: ./caddy
      dockerfile: Dockerfile
    volumes:
      - ./caddy:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CROWDSEC_LOCAL_API_KEY=${CROWDSEC_LOCAL_API_KEY}
    ports:
      - 80:80
      - 443:443

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/home/nonroot/.cloudflared:ro

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    volumes:
      - ${DOCKER_CONFIG_DIR}/crowdsec/data:/var/lib/crowdsec/data
      - ${DOCKER_CONFIG_DIR}/crowdsec/config:/etc/crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/caddy

  my-container:
    container_name: my-container
    image: some/image
    ports:
      - 1234:1234
```

Caddyfile:
```
{
	crowdsec {
		api_url http://crowdsec:8080
		api_key {$CROWDSEC_LOCAL_API_KEY}
	}
	email my@email.com
        acme_dns cloudflare {$CLOUDFLARE_API_TOKEN}
}

my.domain.com {
	route {
		crowdsec
		reverse_proxy my-container:1234
	}
}
```

Caddy Dockerfile:
```
FROM caddy:builder AS builder

RUN xcaddy build \
	# Use Cloudflare for ACME DNS challenge
	--with github.com/caddy-dns/cloudflare \
	# for crowdsec bouncer
    --with github.com/hslatman/caddy-crowdsec-bouncer/http

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Cloudflared config.yml:
```
tunnel: my-tunnel-id
credentials-file: /home/nonroot/.cloudflared/my-tunnel-id.json

ingress:
  - hostname: my.domain.com
    service: https://caddy:443
    originRequest:
      originServerName: "my.domain.com"
  - service: http_status:404
```

thanks!
