### ISSUE TITLE
Working on Oracle arm?

### ISSUE THREAD

**Issue by Vctrsnts** [hslatman/caddy-crowdsec-bouncer#38]
Hi,
I using your docker (crowdsec + caddy) on oracle arm (ubuntu jammy) with docker (25.0) with your docker-comppose.yml (version 3.6):
```
  crowdsec:
    image: crowdsecurity/crowdsec
    ports:
      - "8080:8080"
    volumes:
      - logs:/var/log/nginx/

  caddy:
    build:
      context: ./docker
      target: caddy
    ports:
      - "9443:9443"
      - "8443:8443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - logs:/var/log/caddy
      - ./docker/config.json:/etc/caddy/config.json
```
And using your steps:
- `docker-compose up -d crowdsec`
- `docker-compose exec crowdsec cscli bouncers add caddy-bouncer`
  - And copy the api in `/docker/config.json` "api_key"
- `docker-compose up -d caddy`
- 
But with the las order have this error:
```
7.505 go: upgraded golang.org/x/tools v0.10.0 => v0.14.0
7.509 2024/02/07 21:22:05 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/format-encoder github.com/caddyserver/caddy/v2@v2.7.6 
7.715 go: downloading github.com/caddyserver/format-encoder v0.0.0-20231219065943-58ebafa572d5
7.730 go: github.com/caddyserver/format-encoder@v0.0.0-20231219065943-58ebafa572d5 found: parsing go.mod:
7.730 	module declares its path as: github.com/caddyserver/transform-encoder
7.730 	       but was required as: github.com/caddyserver/format-encoder
7.730 go: github.com/caddyserver/format-encoder@upgrade (v0.0.0-20231219065943-58ebafa572d5) requires github.com/caddyserver/format-encoder@v0.0.0-20231219065943-58ebafa572d5: parsing go.mod:
7.730 	module declares its path as: github.com/caddyserver/transform-encoder
7.730 	       but was required as: github.com/caddyserver/format-encoder
7.731 2024/02/07 21:22:05 [FATAL] exit status 1
------
Dockerfile:11
--------------------
  10 |     
  11 | >>> RUN xcaddy build \
  12 | >>>     --with github.com/mholt/caddy-l4 \
  13 | >>>     --with github.com/caddyserver/format-encoder \
  14 | >>>     --with github.com/hslatman/caddy-crowdsec-bouncer/http@main \
  15 | >>>     --with github.com/hslatman/caddy-crowdsec-bouncer/layer4@main
  16 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c xcaddy build     
--with github.com/mholt/caddy-l4    
--with github.com/caddyserver/format-encoder     
--with github.com/hslatman/caddy-crowdsec-bouncer/http@main     
--with github.com/hslatman/caddy-crowdsec-bouncer/layer4@main" did not complete successfully: exit code: 1
ERROR: Service 'caddy' failed to build : Build failed
```

This docker have a problem with arm? or where is the problem?

And if is possible to work, how next put a url (https://my.web.duckdns.org) go the correct docker, because on **normal Caddyfile** put this:
```
my.web.duckdns.org {
        header X-Robots-Tag "noindex, nofollow"
        reverse_proxy http://10.0.0.209:4000
}
```

Thanks a lot
